import { useState, useEffect } from 'react'

import './Popup.css'

export const Popup = ({testCount}) => {
  const [count, setCount] = useState(testCount || 0)
  const [isLoading, setIsLoading] = useState(true)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const minus = () => {
    if (count > 0){
      setCount(count - 1)
      sendCount(count - 1)
    }
  }

  const add = () => {
    setCount(count + 1)
    sendCount(count + 1)
  }

  useEffect(() => {
    // chrome.runtime.sendMessage({ type: 'getCount' }, () => {
    //   console.log('popup is fetching, result: ' + result)
    //   setCount(result.count)
    //   setIsLoading(false)
    // })
    chrome.storage.sync.get(['count'], (result) => {
      console.log(result)
      setCount(result.count || 0)
    })
  }, [])

  let sendCount = (num) => {
    console.log('popup is sending')
    chrome.runtime.sendMessage({ type: 'setCount', data: { count: num } })
    // chrome.storage.local.get(['count'], (result) => {
    //   console.log(result)
    // })
  }

  return (
    <main>
      <h3>Popup Page</h3>
      <div className="calc">
        <button onClick={minus} disabled={count <= 0}>
          -
        </button>
        {isLoading
        && <label>{count}</label>
        }
        <button onClick={add}>+</button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Popup
